# 服务端口
server:
  port: 8003
# 服务名
spring:
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 环境
  profiles:
    active: dev
  # 最大上传单个文件大小:默认1M
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

aliyun:
  vod:
    file:
      keyid: nihaomiyao
      keysecret: nihaomima

