server:
  port: 8222
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由
      routes[0]:
        id: service-acl
        uri: lb://service-acl
        predicates: Path=/*/acl/**
      routes[1]:
        id: service-edu
        uri: lb://service-edu
        predicates: Path=/eduservice/**
      routes[2]:
        id: service-msm
        uri: lb://service-msm
        predicates: Path=/edumsm/**
      routes[3]:
        id: service-cms
        uri: lb://service-cms
        predicates: Path=/educms/**
      routes[4]:
        id: service-order
        uri: lb://service-order
        predicates: Path=/eduorder/**
      routes[5]:
        id: service-oss
        uri: lb://service-oss
        predicates: Path=/eduoss/**
      routes[6]:
        id: service-statistics
        uri: lb://service-statistics
        predicates: Path=/staservice/**
      routes[7]:
        id: service-vod
        uri: lb://service-vod
        predicates: Path=/eduvod/**
      routes[8]:
        id: service-ucenter
        uri: lb://service-ucenter
        predicates: Path=/educenter/**
