server:
  port: 8004
spring:
  application:
    name: service-cms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.7.237:3306/yuan?serverTimezone=GMT%2B8
    username: root
    password: 123456

# 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        # 最大阻塞等待时间（负数表示没限制）
        max-idle: 5
        min-idle: 0
# 配置mapper xml的文件路径
mybatis-plus:
  mapper-locations: classpath:com/yuan/cmsservice/mapper/xml/*.xml
  # mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

